const ASSET_VERSION = "20260920a";

const PROJECT_FILTERS = [
    { id: "all", label: "All" },
    { id: "game-graphics", label: "Game & Graphics" },
    { id: "finance-data", label: "Finance & Data" },
    { id: "simulation", label: "Simulation" },
    { id: "tools-systems", label: "Tools & Systems" },
];

const SECTION_KEYS = {
    1: "about",
    2: "current",
    3: "experience",
    4: "projects",
    5: "contact",
};

const EXPERIENCE = [
    {
        id: "statistics-canada",
        period: "Sep 2026 – Dec 2026",
        role: "Cloud/Data Developer Co-op",
        organization: "Statistics Canada",
        summary:
            "Working within Statistics Canada’s Digital Solutions Field to support the development and modernization of cloud-based applications and enterprise data services.",
        highlights: [
            "Contributing to application development and cloud-based solutions supporting statistical research across Canada",
            "Collaborating with technical teams and stakeholders in an Agile development environment",
            "Developing Python applications, Azure services, REST APIs, data pipelines, containers, and CI/CD workflows",
        ],
        technologies: [
            "Python",
            "Azure",
            "Docker",
            "Kubernetes / Kubeflow",
            "Git / GitLab",
            "CI/CD",
            "Linux",
            "Data Pipelines",
            "REST APIs",
        ],
        technologyLabel: "Technologies",
        status: "Current Co-op",
    },
    {
        id: "digital-extremes",
        period: "Winter 2026",
        role: "Programmer Co-op",
        organization: "Digital Extremes",
        summary:
            "Worked within a large proprietary C++ game engine, contributing to gameplay features and development tooling in a production environment.",
        highlights: [
            "Designed, debugged, and integrated gameplay features across multiple interconnected engine systems",
            "Investigated complex runtime issues involving state synchronization, system dependencies, and unexpected gameplay behaviour",
            "Collaborated with experienced developers to review, test, and safely integrate changes into an established production codebase",
        ],
        technologies: ["C++", "Proprietary Game Engine", "Git", "Debugging Tools"],
        technologyLabel: "Technologies",
    },
    {
        id: "independent-development",
        period: "Spring 2025",
        role: "Independent Software & Game Developer",
        organization: "Independent and Collaborative Development",
        summary:
            "Dedicated the work term to developing independent software projects and collaborating with a small development team on an original game project.",
        highlights: [
            "Contributed to gameplay programming, combat systems, development tools, technical design, and iterative prototyping",
            "Collaborated on feature planning, responsibility sharing, idea reviews, and version-controlled changes",
            "Designed tools and workflows that made gameplay systems easier to test, debug, and refine",
            "Managed the architecture, scope, and technical challenges of a long-term software project",
        ],
        technologies: ["C++", "Game Development", "Git", "Gameplay Systems", "Tool Development"],
        technologyLabel: "Technologies",
        note: "The original game project remains in development and has not yet been publicly released.",
    },
    {
        id: "waterloo-ai-project",
        period: "Spring 2024",
        role: "AI Project Developer Co-op",
        organization: "University of Waterloo",
        summary:
            "Collaborated remotely on a healthcare-focused artificial intelligence project using Microsoft Azure technologies.",
        highlights: [
            "Contributed to project research, requirements planning, technical implementation, and milestone organization",
            "Helped define project direction, coordinate responsibilities, and present progress and final outcomes",
            "Developed practical Microsoft Azure experience and earned a Microsoft Azure certification during the work term",
        ],
        technologies: ["Microsoft Azure", "Artificial Intelligence", "Cloud Computing", "Project Planning"],
        technologyLabel: "Technologies",
    },
];

const INVOLVEMENT = {
    title: "Game Jams and Hackathons",
    summary:
        "Participated in collaborative game-development, hackathon-style, and technical activities through school and community groups.",
    highlights: [
        "Worked with teams to develop project ideas and prototypes",
        "Contributed to programming, planning, problem-solving, and presentations",
        "Developed early experience collaborating on technical projects and working within project constraints",
    ],
};

const PROJECTS = [
    {
        id: "valuation-deal-lab",
        title: "Valuation & Deal Lab",
        summary:
            "Source-traceable corporate valuation application that converts SEC EDGAR filings into DCF, peer-multiple, M&A, and formula-reconciled Excel models.",
        categories: ["finance-data", "tools-systems"],
        image: "assets/images/projects/valuation-deal-lab/dcf_sensitivity_analysis.png",
        imageAlt: "Valuation and Deal Lab DCF forecast, valuation bridge, and sensitivity schedules",
        languages: ["Python"],
        techStack: [
            "Python 3.12+",
            "pandas",
            "NumPy",
            "Streamlit",
            "Plotly",
            "Pydantic",
            "XlsxWriter",
            "openpyxl",
            "SEC EDGAR",
            "Ollama",
            "Pytest",
        ],
        features: [
            "Ingests SEC EDGAR XBRL filings through a rate-limited client and audited YAML concept mappings with accession-level provenance",
            "Builds five-year operating forecasts, Gordon-growth DCF models, equity value bridges, and two-dimensional WACC and terminal-growth sensitivity matrices",
            "Calculates peer EV/Revenue, EV/EBITDA, P/E, and Price/FCF multiples with quartile distributions and football-field valuation ranges",
            "Models cash, debt, and equity M&A financing with first-year and run-rate EPS accretion/dilution, pro forma leverage, and synergy breakeven",
            "Exports formula-driven nine-sheet Excel workbooks verified against Python outputs with openpyxl reconciliation tests",
            "Generates schema-constrained local Ollama commentary with citation, numerical-precision, and narrative-direction checks",
            "Presents the model through a worksheet-tabbed Streamlit interface with financial-statement formatting and data-integrity checks",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/valuation-deal-lab/dcf_sensitivity_analysis.png",
            "assets/images/projects/valuation-deal-lab/deal_model_ai_explanation.png",
            "assets/images/projects/valuation-deal-lab/comparable_companies_football_field.png",
            "assets/images/projects/valuation-deal-lab/historical_company_overview.png",
        ],
    },
    {
        id: "credit-decision-lab",
        title: "Credit Decision Lab",
        summary:
            "Credit underwriting and evaluation application combining calibrated default prediction, empirical policy thresholds, Monte Carlo stress simulation, and metadata persistence.",
        categories: ["finance-data", "simulation", "tools-systems"],
        image: "assets/images/projects/credit-decision-lab/dashboard.png",
        imageAlt: "Credit Decision Lab case review with applicant risk and repayment data",
        languages: ["Python", "SQL"],
        techStack: [
            "Python 3.12",
            "Pandas",
            "NumPy",
            "SciPy",
            "scikit-learn",
            "Streamlit",
            "Plotly",
            "FastAPI",
            "Pydantic",
            "SQLAlchemy",
            "PostgreSQL",
            "MLflow",
            "Docker Compose",
            "Pytest",
        ],
        features: [
            "Compares logistic regression and gradient boosting with Platt sigmoid and isotonic calibration selected by validation Brier score",
            "Optimizes empirical default-risk cutoffs against credit exposure, performing margins, loss severity, and portfolio default-rate caps",
            "Runs chunked Monte Carlo portfolio simulations with loss distributions, 95% and 99% Value at Risk, and Expected Shortfall under logit-stressed scenarios",
            "Evaluates Brier permutation importance, standardized coefficients, risk-band calibration gaps, boundary sensitivity, and high-confidence errors",
            "Serves batch inference and policy simulation through strict FastAPI/Pydantic schemas with privacy-preserving PostgreSQL metadata logging",
            "Provides seven Streamlit analysis screens with case dossiers, six-month repayment ledgers, reliability curves, and policy-frontier inspection",
            "Uses Docker Compose, PostgreSQL, MLflow, Alembic migrations, synthetic drift monitoring, and Pytest coverage",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/credit-decision-lab/dashboard.png",
            "assets/images/projects/credit-decision-lab/approval-policy.png",
            "assets/images/projects/credit-decision-lab/calibration.png",
            "assets/images/projects/credit-decision-lab/portfolio-simulation.png",
        ],
    },
    {
        id: "graphics-rasterizer",
        title: "3D Graphics Rasterizer",
        summary: "From-scratch software 3D renderer with a full rasterization pipeline and live GUI.",
        categories: ["game-graphics", "tools-systems"],
        image: "assets/images/projects/3d-graphics-rasterizer/textured.webp",
        imageAlt: "Textured model rendered in the software rasterizer",
        languages: ["C++"],
        techStack: ["C++", "SDL2", "ImGui", "TGAImage", "Catch2"],
        features: [
            "Built a complete rasterization pipeline from vertex processing to fragment shading",
            "Implemented triangle rasterization with barycentric interpolation",
            "Developed a custom shader pipeline supporting diffuse, normal, and specular mapping",
            "Added Phong lighting for realistic shading and highlights",
            "Integrated ImGui for real-time parameter tweaking without recompilation",
            "Used TGAImage for texture loading",
            "Optimized rendering with backface culling",
        ],
        github: { url: "https://github.com/wrgdevs/software-rasterizer", label: "View on GitHub" },
        images: [
            "assets/images/projects/3d-graphics-rasterizer/textured.webp",
            "assets/images/projects/3d-graphics-rasterizer/normal_map.webp",
            "assets/images/projects/3d-graphics-rasterizer/Wireframe.webp",
            "assets/images/projects/3d-graphics-rasterizer/specular.webp",
        ],
    },
    {
        id: "custom-ecs-game-engine",
        title: "Custom ECS Game Engine",
        summary:
            "Lightweight C++ game engine with ECS architecture, editor tooling, Lua scripting, scene serialization, and runtime export.",
        categories: ["game-graphics", "tools-systems"],
        image: "assets/images/projects/custom-ecs-game-engine/editor.webp",
        imageAlt: "Custom ECS game engine editor interface",
        languages: ["C++", "Lua"],
        techStack: ["C++20", "CMake", "SDL2", "OpenGL", "ImGui", "Lua", "EnTT", "GLM", "JSON", "stb_image"],
        features: [
            "Built modular C++20 engine architecture with ECS-based scene, entity, and component management",
            "Created ImGui editor with scene hierarchy, inspector, viewport, asset browser, prefab browser, and runtime preview",
            "Implemented JSON scene and prefab serialization with reusable entity prefabs",
            "Added Lua scripting, animation, audio playback, physics, collision, undo, redo, and event systems",
            "Developed a resource manager with texture and audio caching",
            "Built standalone runtime export pipeline to separate editor tooling from playable builds",
        ],
        github: { url: "https://github.com/wrgdevs/CustomECSEngine", label: "View on GitHub" },
        images: [
            "assets/images/projects/custom-ecs-game-engine/editor.webp",
            "assets/images/projects/custom-ecs-game-engine/prefab.webp",
            "assets/images/projects/custom-ecs-game-engine/transform.webp",
            "assets/images/projects/custom-ecs-game-engine/animation.webp",
        ],
    },
    {
        id: "procedural-terrain-generator",
        title: "Procedural Terrain Generator",
        summary: "Real-time 3D terrain engine with infinite streaming and erosion simulation.",
        categories: ["game-graphics", "simulation"],
        image: "assets/images/projects/procedural-terrain-generator/mount.webp",
        imageAlt: "Generated mountain terrain",
        languages: ["TypeScript"],
        techStack: ["TypeScript", "React", "Three.js", "WebGL", "Vite"],
        features: [
            "Built multi-layer noise generation with domain warping for natural landforms",
            "Implemented level-of-detail system for performance at large scales",
            "Added hydraulic erosion simulation for realistic terrain shaping",
            "Developed infinite terrain streaming with dynamic chunk loading",
            "Created biome blending using temperature and moisture maps",
        ],
        github: { url: "https://github.com/wrgdevs/procedural-terrain-generator", label: "View on GitHub" },
        images: [
            "assets/images/projects/procedural-terrain-generator/mount.webp",
            "assets/images/projects/procedural-terrain-generator/island.webp",
            "assets/images/projects/procedural-terrain-generator/desert.webp",
        ],
    },
    {
        id: "world-economy-simulator",
        title: "World Economy Simulator",
        summary:
            "Deterministic multi-country economic simulator for bilateral trade, fiscal policy, supply shocks, and reproducible counterfactual scenarios.",
        categories: ["simulation", "finance-data"],
        image: "assets/images/projects/world-economy-simulator/eco2.webp",
        imageAlt: "World economy simulator bilateral trade network and sector policy controls",
        languages: ["TypeScript"],
        techStack: ["TypeScript", "React 19", "Vite", "Chart.js", "HTML5 Canvas / SVG", "Web Storage API"],
        features: [
            "Models production, consumption, debt service, inflation, and migration with a deterministic discrete-step engine",
            "Routes multiple commodities across bilateral trade links using regional deficits, transport losses, tariffs, and partner priorities",
            "Runs side-by-side A/B policy scenarios against identical random seeds with synchronized divergence tables",
            "Renders trade corridors, flow vectors, commodity volumes, and supply-shock disruptions as an interactive SVG network",
            "Supports point-in-time inspection with timeline scrubbing, shock markers, playback controls, and CSV export",
            "Adjusts spending, taxation, and tariffs with proportional feedback rules targeting debt-to-wealth and happiness thresholds",
        ],
        github: { url: "https://github.com/wrgdevs/world-economy-simulator", label: "View on GitHub" },
        images: [
            "assets/images/projects/world-economy-simulator/eco2.webp",
            "assets/images/projects/world-economy-simulator/eco3.webp",
            "assets/images/projects/world-economy-simulator/eco4.webp",
            "assets/images/projects/world-economy-simulator/eco1.webp",
        ],
    },
    {
        id: "algorithmic-trading-backtester",
        title: "Algorithmic Trading Backtester",
        summary:
            "Multi-asset quantitative backtester with daily-bar execution, transaction costs, AST-validated custom rules, and walk-forward out-of-sample analysis.",
        categories: ["finance-data"],
        image: "assets/images/projects/algorithmic-trading-backtester/charts.webp",
        imageAlt: "Backtest and benchmark equity curves with monthly return distribution",
        languages: ["Python"],
        techStack: ["Python 3.14", "Streamlit", "NumPy", "Pandas", "Plotly", "SciPy", "Pytest", "Playwright"],
        features: [
            "Simulates daily multi-asset strategies with commission, slippage, leverage limits, volatility targeting, and configurable rebalancing",
            "Evaluates rolling and expanding walk-forward folds with warm-up isolation and continuous capital across window transitions",
            "Tracks out-of-sample Sharpe decay, parameter-selection stability, and turnover across validation folds",
            "Parses custom rules through an AST validator and computes signals from twenty-one technical indicators without eval",
            "Reports benchmark-relative alpha and beta, historical and parametric VaR/CVaR, drawdowns, win rates, and rolling risk-adjusted returns",
            "Includes fourteen strategies spanning cross-sectional momentum, cointegrated pairs, regime-switching trend filters, Bollinger mean reversion, and inverse volatility",
        ],
        github: { url: "https://github.com/wrgdevs/algorithmic-trading-backtester", label: "View on GitHub" },
        images: [
            "assets/images/projects/algorithmic-trading-backtester/charts.webp",
            "assets/images/projects/algorithmic-trading-backtester/validation.webp",
            "assets/images/projects/algorithmic-trading-backtester/charts-more.webp",
            "assets/images/projects/algorithmic-trading-backtester/signal.webp",
            "assets/images/projects/algorithmic-trading-backtester/weights.webp",
        ],
    },
    {
        id: "banking-transaction-ledger",
        title: "Banking Transaction Ledger",
        summary:
            "Full-stack banking ledger with immutable double-entry accounting, concurrency control, idempotent operations, authorization, and reconciliation.",
        categories: ["finance-data", "tools-systems"],
        image: "assets/images/projects/bank-ledger/overview.webp",
        imageAlt: "Banking transaction ledger account overview and recent entries",
        languages: ["C#", "TypeScript", "SQL"],
        techStack: [
            "ASP.NET Core 9",
            "React 19",
            "TypeScript",
            "PostgreSQL",
            "Entity Framework Core",
            "SQLite",
            "Docker Compose",
            "Vite",
            "Testcontainers",
            "xUnit",
            "Nginx",
        ],
        features: [
            "Generates balanced immutable debit and credit entries atomically for deposits, withdrawals, and transfers",
            "Uses PostgreSQL xmin row-version tokens and database transactions to prevent race conditions and concurrent double spending",
            "Replays exact idempotent retries, rejects conflicting key reuse with HTTP 409, and persists failed attempts",
            "Enforces signed JWT authentication, customer ownership boundaries, and separate Admin and Auditor policies",
            "Reconciles transaction balance equality and cached account balances against calculated ledger-entry sums",
            "Provides transaction filtering, debit/credit tables, and monthly CSV or JSON statement generation through a React/TypeScript client",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/bank-ledger/overview.webp",
            "assets/images/projects/bank-ledger/transactions.webp",
            "assets/images/projects/bank-ledger/statements.webp",
            "assets/images/projects/bank-ledger/login.webp",
        ],
    },

    {
        id: "market-replay-lab",
        title: "Market Replay Lab",
        summary:
            "Historical market replay tool that reconstructs point-in-time price action, state transitions, and simulated execution without future-data leakage.",
        categories: ["finance-data", "tools-systems"],
        image: "assets/images/projects/market-replay-terminal/replay.webp",
        imageAlt: "Market Replay Lab interactive candlestick replay and inspector workspace",
        languages: ["TypeScript", "Python"],
        techStack: ["React", "TypeScript", "FastAPI", "SQLite", "SQLAlchemy", "yfinance", "Vite"],
        features: [
            "Enforces causal boundaries so charts, rolling VWAP, RVOL, and analytics never derive from bars beyond the active cursor",
            "Logs channel penetrations and session gaps as chronological state transitions while suppressing duplicate trend events",
            "Renders SVG candlesticks, volume, moving averages, bar inspection, revealed-history scrubbing, and timestamped bookmarks",
            "Simulates market and limit orders with fixed spreads, slippage, volume-participation limits, and rewind rollback",
            "Computes bar-return distributions, intraday volatility evolution, and estimated volume-at-price profiles with explicit uniform-distribution assumptions",
            "Persists one-minute and daily OHLCV data in SQLite with Yahoo Finance ingestion and custom CSV imports",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/market-replay-terminal/replay.webp",
            "assets/images/projects/market-replay-terminal/portfolio.webp",
            "assets/images/projects/market-replay-terminal/stratlab.webp",
            "assets/images/projects/market-replay-terminal/data.webp",
        ],
    },
    {
        id: "neural-network-from-scratch",
        title: "Neural Network from Scratch",
        summary:
            "Pure-NumPy MNIST classifier with configurable training, checkpoint persistence, numerical gradient verification, and model-inspection views.",
        categories: ["finance-data", "tools-systems"],
        image: "assets/images/projects/neural-network-from-scratch/learn1.webp",
        imageAlt: "Neural network training visualization",
        languages: ["Python"],
        techStack: ["NumPy", "Matplotlib", "pandas", "Streamlit", "setuptools", "pytest"],
        features: [
            "Implements configurable dense MNIST classifiers without a machine-learning framework",
            "Supports ReLU, LeakyReLU, Sigmoid, Tanh, Softmax, He/Xavier initialization, and categorical cross-entropy",
            "Includes SGD, momentum, Adam, dropout, L2 regularization, learning-rate decay, early stopping, and checkpoints",
            "Provides CLI training, evaluation, and activation, learning-rate, and optimizer comparisons with CSV summaries",
            "Verifies gradients through deterministic central finite differences with parameter-restoration tests",
            "Offers Streamlit Train, Evaluate, Inspect, and About views with learning curves, confusion matrices, predictions, error tables, and class probabilities",
        ],
        github: { url: "https://github.com/wrgdevs/nn-from-scratch-cli", label: "View on GitHub" },
        images: [
            "assets/images/projects/neural-network-from-scratch/learn1.webp",
            "assets/images/projects/neural-network-from-scratch/learn2.webp",
            "assets/images/projects/neural-network-from-scratch/learn3.webp",
        ],
    },
    {
        id: "procedural-dungeon-map-generator",
        title: "Procedural Dungeon Map Generator",
        summary: "C++ dungeon generator with five algorithms, SDL2 visualization, map statistics, and JSON export.",
        categories: ["game-graphics", "simulation"],
        image: "assets/images/projects/procedural-dungeon-map-generator/dun1.webp",
        imageAlt: "Procedural dungeon map visualization",
        languages: ["C++"],
        techStack: ["C++17/20", "SDL2", "SDL2_ttf", "nlohmann::json", "Multithreading"],
        features: [
            "Implemented five generation algorithms including BSP, Cellular Automata, Drunkard's Walk, Recursive Backtracker, and Random Rooms",
            "Built live SDL2 renderer with pan, zoom, and overlay analytics",
            "Added real-time map statistics for floor coverage, connectivity, and largest region",
            "Enabled keyboard-controlled parameter tweaking and instant algorithm switching",
            "Created JSON export system using nlohmann::json for map persistence",
        ],
        github: { url: "https://github.com/wrgdevs/dungeonMapGen", label: "View on GitHub" },
        images: [
            "assets/images/projects/procedural-dungeon-map-generator/dun1.webp",
            "assets/images/projects/procedural-dungeon-map-generator/dun2.webp",
            "assets/images/projects/procedural-dungeon-map-generator/dun3.webp",
        ],
    },
    {
        id: "ecosystem-simulation",
        title: "Ecosystem Simulation",
        summary:
            "Multithreaded 2D ecosystem simulation of plants, prey, predators, population density, and flocking behavior.",
        categories: ["simulation"],
        image: "assets/images/projects/ecosystem-simulation/eco1.webp",
        imageAlt: "Ecosystem simulation screen",
        languages: ["C++"],
        techStack: ["C++17", "SDL2", "SDL2_ttf", "Custom ECS", "Multithreading"],
        features: [
            "Developed interactive SDL2 visualization with dynamic HUD and mouse-over info",
            "Built a multithreaded simulation architecture using a custom thread pool and job system",
            "Built species entities with energy, metabolism, vision, speed, and reproduction traits",
            "Implemented emergent flocking and clustering behaviors",
            "Added heatmaps and density overlays for population analysis",
            "Created trail rendering and dynamic camera system using SDL2",
        ],
        github: { url: "https://github.com/wrgdevs/EcoSim", label: "View on GitHub" },
        images: [
            "assets/images/projects/ecosystem-simulation/eco1.webp",
            "assets/images/projects/ecosystem-simulation/eco2.webp",
            "assets/images/projects/ecosystem-simulation/eco3.webp",
        ],
    },
    {
        id: "monte-carlo-portfolio-simulator",
        title: "Monte Carlo Portfolio Simulator",
        summary:
            "Local portfolio simulator combining historically calibrated correlated GBM, bootstrap and stress analysis, risk-neutral option pricing, and exportable reports.",
        categories: ["finance-data", "simulation"],
        image: "assets/images/projects/monte-carlo-portfolio-simulator/Monte1.webp",
        imageAlt: "Monte Carlo portfolio distribution, allocation, and tail-risk report",
        languages: ["Python"],
        techStack: ["Python", "NumPy", "pandas", "Matplotlib", "Plotly", "Streamlit", "yfinance", "pytest"],
        features: [
            "Calibrates annualized returns, volatility, covariance, and correlation from historical log returns for correlated multi-asset simulation",
            "Prices European and arithmetic Asian options under risk-neutral GBM with Monte Carlo uncertainty and Black-Scholes comparisons",
            "Estimates Delta and one-volatility-point Vega with common random numbers and reports path-count convergence",
            "Computes terminal percentiles, explicit loss equivalents, loss probability, Sharpe/Sortino ratios, drawdowns, bootstrap comparisons, and shocks",
            "Samples long-only allocations to identify maximum-Sharpe and minimum-volatility portfolios",
            "Provides reproducible Streamlit and CLI workflows with JSON, HTML, and PNG exports",
        ],
        github: { url: "https://github.com/wrgdevs/monte-carlo-portfolio-simulator", label: "View on GitHub" },
        images: [
            "assets/images/projects/monte-carlo-portfolio-simulator/Monte1.webp",
            "assets/images/projects/monte-carlo-portfolio-simulator/Monte2.webp",
            "assets/images/projects/monte-carlo-portfolio-simulator/Monte3.webp",
            "assets/images/projects/monte-carlo-portfolio-simulator/Monte4.webp",
        ],
    },
    {
        id: "steam-game-analytics",
        title: "Steam Game Analytics",
        summary:
            "Steam catalog analytics and recommendation tool with TF-IDF similarity, ambiguity-safe title matching, CLI workflows, and a Streamlit catalog explorer.",
        categories: ["finance-data"],
        image: "assets/images/projects/steam-game-analytics/Ana1.webp",
        imageAlt: "Steam catalog discovery and recommendation explorer",
        languages: ["Python"],
        techStack: ["Python", "Pandas", "NumPy", "scikit-learn", "RapidFuzz", "Click", "Streamlit", "Matplotlib"],
        features: [
            "Resolves titles with exact-first and token-sorted matching, confidence margins, and disambiguation alternatives",
            "Builds content-based recommendations with TF-IDF cosine similarity and thread-safe weak-reference caching",
            "Compares price, review volume, rating deltas, and shared or unique genres across selected games",
            "Normalizes free titles, preserves missing prices, and computes correlations, price buckets, and multi-genre aggregates",
            "Provides eighteen Click CLI commands plus a full-width Streamlit catalog explorer with filtering, currency detection, and CSV export",
            "Tests data cleaning, fuzzy thresholds, similarity memoization, plots, and headless Streamlit execution",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/steam-game-analytics/Ana1.webp",
            "assets/images/projects/steam-game-analytics/Ana2.webp",
            "assets/images/projects/steam-game-analytics/Ana3.webp",
        ],
    },
    {
        id: "two-d-game-editor",
        title: "2D Game Editor",
        summary:
            "C++ level editor with tile editing, JSON serialization, Lua scripting, and in-editor physics previews.",
        categories: ["game-graphics", "tools-systems"],
        image: "assets/images/projects/2d-game-editor/Menu.webp",
        imageAlt: "2D game editor menu",
        languages: ["C++"],
        techStack: ["C++", "SDL2", "ImGui", "Lua", "JSON"],
        features: [
            "Built save and load workflows with JSON serialization for map import and export",
            "Implemented real-time tile editing with immediate visual feedback using SDL2",
            "Developed a camera system with zoom and pan controls",
            "Created grid snapping and spatial editing tools",
            "Added in-editor physics preview using AABB collision and raycasting",
            "Integrated ImGui for real-time UI and parameter adjustments",
            "Added Lua scripting for level behavior",
        ],
        github: { url: "https://github.com/chilly-nap/Hooked-on-Speed", label: "View on GitHub (older version)" },
        images: ["assets/images/projects/2d-game-editor/Menu.webp", "assets/images/projects/2d-game-editor/Game.webp"],
    },
    {
        id: "tactical-rpg",
        title: "Tactical RPG",
        summary: "Chess-inspired grid-based tactical RPG with modular classes.",
        categories: ["game-graphics"],
        image: "assets/images/projects/tactical-rpg/Chess.webp",
        imageAlt: "Tactical RPG board",
        languages: ["C#"],
        techStack: ["C#", "Unity Engine"],
        features: [
            "Implemented grid movement validation with chess-style rule enforcement",
            "Built class-specific abilities such as teleport, shield blocking, and area spells",
            "Developed a modular character system with customizable stats and progression",
            "Created turn-based gameplay logic with explicit action and state management",
            "Designed a board system supporting variable map sizes",
        ],
        github: { label: "Repository coming soon" },
        images: ["assets/images/projects/tactical-rpg/Chess.webp"],
    },
    {
        id: "shogi-learning-app",
        title: "Shogi Learning App",
        summary: "Interactive Shogi tutor with tutorials, puzzles, and progress tracking.",
        categories: ["tools-systems"],
        image: "assets/images/projects/shogi-learning-app/Tutorial.webp",
        imageAlt: "Shogi learning app tutorial screen",
        languages: ["Java"],
        techStack: ["Java", "Swing", "JUnit"],
        features: [
            "Built step-by-step tutorial system covering rules, piece movement, and board setup",
            "Created interactive GUI to visualize piece movement and captures using Swing",
            "Designed progressive puzzle challenges to reinforce learning concepts",
            "Implemented progress tracking and milestones",
            "Added a modular lesson structure for extending tutorial content",
        ],
        github: { label: "Repository coming soon" },
        images: [
            "assets/images/projects/shogi-learning-app/Teach.webp",
            "assets/images/projects/shogi-learning-app/Tutorial.webp",
        ],
    },
    {
        id: "chip8-emulator",
        title: "CHIP-8 Emulator",
        summary: "C++ CHIP-8 emulator with opcode execution, keypad input, stack handling, and SDL2 display output.",
        categories: ["tools-systems", "game-graphics"],
        image: "assets/images/projects/chip8-emulator/game1.webp",
        imageAlt: "CHIP-8 emulator game screen",
        languages: ["C++"],
        techStack: ["C++", "SDL2"],
        features: [
            "Recreated CHIP-8 architecture including memory, registers, stack, and program counter",
            "Implemented instruction set interpreter for opcode execution",
            "Built real-time 64x32 monochrome display rendering with SDL2",
            "Added hexadecimal keypad input mapping to keyboard controls",
            "Developed stack system supporting subroutine calls and returns",
        ],
        github: { label: "Repository coming soon" },
        images: ["assets/images/projects/chip8-emulator/game1.webp"],
    },
];

const HEADER_TITLE = "WEI RONG GAO";
const HEADER_SUBTITLE = "MATHEMATICS @ WATERLOO // SOFTWARE • DATA • SIMULATION";

export {
    ASSET_VERSION,
    EXPERIENCE,
    HEADER_SUBTITLE,
    HEADER_TITLE,
    INVOLVEMENT,
    PROJECT_FILTERS,
    PROJECTS,
    SECTION_KEYS,
};
